### ISSUE TITLE
Difference between SoarGfs and SoarV2

### ISSUE THREAD

**Issue by gzoritchak** [soaringmeteo/soaringmeteo#91] opened 2023-09-29 07:11 UTC
I was surprised by the differences between those models. I was expecting a convergence of the results.

If I take today (29.09.2023) forecast for today and tomorrow (30.09.2023)
 
 
<img width="729" alt="CleanShot 2023-09-29 at 09 08 52@2x" src="https://github.com/soaringmeteo/soaringmeteo/assets/1110254/b57cd2e4-ea9d-42cb-8db2-e56d500daa9d">

<img width="752" alt="CleanShot 2023-09-29 at 09 09 14@2x" src="https://github.com/soaringmeteo/soaringmeteo/assets/1110254/76155774-57c6-4c50-a999-96ccb6cc8abe">

<img width="789" alt="CleanShot 2023-09-29 at 09 09 57@2x" src="https://github.com/soaringmeteo/soaringmeteo/assets/1110254/2f5c0408-b87b-4b7d-9cfb-23e278d22ec7">

<img width="752" alt="CleanShot 2023-09-29 at 09 10 22@2x" src="https://github.com/soaringmeteo/soaringmeteo/assets/1110254/69e1eb1f-1bdb-4d73-9ac7-2c498bd7cbe2">

The forecast seems inverted: it's better today on GFS and tomorrow on SoarV2.

**Comment by julienrf** [comment] 2023-09-29 11:53
You are comparing **soarWRF** with soarV2 (which currently shows the results of the GFS0.25 model). The differences may come from the following reasons:

- The “run” is not the same (ie, WRF was initialized with data different from what you display in soarV2),
- Due to the grid higher resolution, WRF is able to show local effects, whereas GFS provides mesoscale results only,
- The formula to compute the XC flying potential (in soarV2) and Thermal Quality (in soarWRF) are not 100% the same.

If the third reason is the one that applies here, this is a problem. We should double-check the formulas and understand why they give different results.

Here, it is possible that the first two points apply. If I use the same initialization time (28th September, 12:00 UTC), I see the following results for Saturday in soarV2:

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/71decf33-8531-415b-bdb4-cd82b60b2ef0)

Still pretty different from what WRF gives. Let’s look at differences that may come from underlying grid resolution.

Here is the detailed information we get from the GFS model:

![Screenshot 2023-09-29 at 13-39-18 SoaringMeteo](https://github.com/soaringmeteo/soaringmeteo/assets/332812/66503154-74d3-4d15-9595-4a88cd2169ee)

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/4f907fca-d2b0-450b-9395-e01ad1df5697)

And the equivalent information we get from WRF at the closest location:

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/13e48e5f-cf44-4577-800d-3dd22f2539b0)

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/4b62cbde-c382-42da-a189-8ee5a31a1514)

It is interesting to see that in both cases the boundary layer ceiling is very similar: 1705 m for GFS vs 1694 m for WRF. However, the terrain model in GFS is coarser-grained: the altitude of the ground is 864 m in GFS, vs 1280 m in WRF, which means that in this case, GFS will overestimate the soaring layer depth (841 m vs 414 m in WRF). I believe this is the main reason for the difference you observe between soarWRF and soarV2, for this point.

We can look at another point, south to Annecy lake, for which we see an important difference between GFS and WRF:

![image](https://github.com/soaringmeteo/soaringmeteo/assets/332812/a503db1e-41df-4506-b60a-ede69f08cf17)

Here, we see that the wind speed is pretty different between GFS and WRF. I believe this is because that point is in a narrow valley that is not modeled in GFS. However, WRF is able to predict the valley breeze there.

I hope that helps! In summary, I think most of the differences we see in this example are due to the resolution of the underlying models (25 km vs 2 km), which is expected. However, we should keep watching out for unexpected differences, which may be caused by slight differences in the formulas used to compute the XC flying potential and the thermal quality.

**Comment by julienrf** [comment] 2023-09-29 11:57
I am closing this issue because I think the differences you observed are expected, but feel free to re-open in case you find something suspicious!

**Closed by julienrf** 2023-09-29 11:57 UTC
